export interface passengerState {
  passengers: any;
  flightNumber: string;
}
export interface passengerinterface {
  id: number;
  passengerId: number;
  passengerName: string;
  flightNumber: string;
  seatNumber: number;
  ancillaryService: string;
  checkedIn: boolean;
}
export const passengerInitialState: passengerState = {
  passengers: [
    {
      passengerId: 1,
      passengerName: 'Sagar',
      flightNumber: 'b1345',
      seatNumber: 1,
      ancillaryService: 'medical',
      checkedIn: true,
      wheelChair: true,
      infant: false,
      mealsService: 'Grade1',
      passportNumber: 'MYUEPS589',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 2,
      passengerName: 'Bhoomika',
      flightNumber: 'b1345',
      seatNumber: 15,
      ancillaryService: 'Drinks',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: false,
      infant: false,
      passportNumber: 'GfdfYUEPS589',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 3,
      passengerName: 'Asha',
      flightNumber: 'C1234',
      seatNumber: 16,
      ancillaryService: 'Drinks',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: true,
      infant: false,
      passportNumber: 'HYUG^&*&*',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },

    {
      passengerId: 4,
      passengerName: 'Mahesh',
      flightNumber: 'b1345',
      seatNumber: 10,
      ancillaryService: 'Drinks',
      mealsService: 'Grade2',
      checkedIn: false,
      wheelChair: false,
      infant: false,
      passportNumber: '',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 5,
      passengerName: 'Surya',
      flightNumber: 'b1341',
      seatNumber: 16,
      ancillaryService: 'Biscuts',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: true,
      infant: false,
      passportNumber: '',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 6,
      passengerName: 'Sagar',
      flightNumber: 'b1341',
      seatNumber: 8,
      ancillaryService: 'Biscuts',
      mealsService: 'Grade1',
      checkedIn: false,
      wheelChair: false,
      infant: false,
      passportNumber: 'tYUVEPS589',
      address: '',
      dateOfBirth: '',
    },
    {
      passengerId: 7,
      passengerName: 'Jenki',
      flightNumber: 'b1345',
      seatNumber: 19,
      ancillaryService: 'Biscuts',
      mealsService: 'Grade3',
      checkedIn: true,
      wheelChair: false,
      infant: false,
      passportNumber: '',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 8,
      passengerName: 'Kiran',
      flightNumber: 'b1341',
      seatNumber: 11,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: false,
      infant: false,
      passportNumber: 'Ug^*^**&6',
      address: '',
      dateOfBirth: '',
    },
    {
      passengerId: 9,
      passengerName: 'Sathish',
      flightNumber: 'b1341',
      seatNumber: 10,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: false,
      infant: true,
      passportNumber: 'YUJG^%^&&*',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '',
    },
    {
      passengerId: 10,
      passengerName: 'Powera',
      flightNumber: 'b1341',
      seatNumber: 19,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: false,
      wheelChair: false,
      infant: false,
      passportNumber: '',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 11,
      passengerName: 'Showya',
      flightNumber: 'b1341',
      seatNumber: 5,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: false,
      infant: false,
      passportNumber: 'GYUEPS589',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 12,
      passengerName: 'Usha',
      flightNumber: 'C1234',
      seatNumber: 17,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: true,
      infant: false,
      passportNumber: 'GYUEPS589',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 13,
      passengerName: 'Krisha',
      flightNumber: 'C1234',
      seatNumber: 18,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: false,
      wheelChair: false,
      infant: true,
      passportNumber: 'GYUEPS589',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '',
    },
    {
      passengerId: 14,
      passengerName: 'Loha',
      flightNumber: 'C1234',
      seatNumber: 19,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: true,
      wheelChair: false,
      infant: false,
      passportNumber: 'KUTYV7878',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '20-06-1998',
    },
    {
      passengerId: 15,
      passengerName: 'harish',
      flightNumber: 'C1234',
      seatNumber: 11,
      ancillaryService: 'Special drinks',
      mealsService: 'Grade1',
      checkedIn: false,
      wheelChair: false,
      infant: false,
      passportNumber: 'GYUEPS589',
      address: 'Ktsasa s uyjash',
      dateOfBirth: '',
    },
  ],
  flightNumber: '0',
};
